library("tidyverse")
library("furrr")
 plan(multiprocess)
## SWEEP RUN CODE
## This if you want to run the sweep
#library("deSolve")
#
#source("model.R")
#source("parms.R")
#
 range_r <- seq(0.1, 2, 0.1)
 range_d <- seq(0.1, 0.9, 0.1)
 range_a <- seq(0.01, 0.2, 0.01)
 subspace <- crossing(rprf1 = range_r, dere = range_d, a_ = range_a)
#
#sweep_ <- subspace %>%
#  mutate(outs = future_pmap(list(1, rprf1, dere, a_),
#                            function(x, y, z, l) mollo(x, y, z, l)
#                            )
#        )
#
## This if you want to load a sweep file
## (an rds generated by the above "Sweep run" code)
sweep_ <- readRDS("out.rds")

lsw <- sweep_ %>%
   mutate(louts = future_map(outs, ~as.vector(tail(.x, 1))[-1])) %>%
   mutate(louts = future_map(louts, setNames, c("P", "f1"))) %>%
   unnest_wider(louts)

lsw_a <-  lsw %>%
   select(-outs) %>%
   pivot_longer(-c(rprf1, dere, a_))
 
#off saveRDS(lsw_a, "out.rds")
